using static System.Console;
int a, b, c;
bool pergunta1, pergunta2, pergunta3, pergunta4;
Write("Digite o primeiro valor: ");
a = int.Parse(ReadLine());
Write("Digite o segundo valor: ");
b = int.Parse(ReadLine());
Write("Digite o terceiro valor: ");
c = int.Parse(ReadLine());
pergunta1 = (a == c);
pergunta2 = (b != a);
pergunta3 = (b > c);
pergunta4 = (a <= c);
WriteLine($"O primeiro valor é igual ao terceiro valor: {pergunta1}");
WriteLine($"O segundo valor é diferente do primeiro valor: {pergunta2}");
WriteLine($"O segundo valor é maior que o terceiro valor: {pergunta3}");
WriteLine($"O primeiro valor é menor ou igual ao terceiro valor: {pergunta4}");
bool primeiraETerceira = pergunta1 && pergunta3;
bool segundaOUQuarta = pergunta2 || pergunta4;
bool negacaoPrimeira = !pergunta1;
WriteLine("A 1ª e a 3ª perguntas são verdadeiras");
WriteLine("A 2ª e a 4ª pergunta, pelo menos uma é verdadeira");
WriteLine("Se a negação da primeira pergunta é verdadeira");